# Generated by Django 5.1.6 on 2025-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
