# Generated by Django 5.1.6 on 2025-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
