# Generated by Django 5.1.6 on 2025-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("created_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
