# Generated by Django 5.1.6 on 2025-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_remove_task_is_completed_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtask",
            name="is_completed",
            field=models.BooleanField(default=True),
        ),
    ]
