# Generated by Django 5.1.6 on 2025-04-05 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_alter_completedtask_user_alter_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedtask",
            name="user",
        ),
    ]
